### ISSUE TITLE
Bug: Can't click on buttons in sheet components using touch devices

### ISSUE THREAD

**Issue by hasanparasteh** [kadiryazici/bottom-sheet-vue3#10]
There's something weird going on with `Sheet` component. I can freely click on anything that's inside of a `Sheet` component but only and only on `Desktop Operating Systems` like MacOs or Linux or Windows and etc.

I can't trigger `onclick` or any other thing inside sheet with mobile devices (touch devices)!

### How to reproduce

Just cloned the project from `main` branch and run `npm run dev -- --host`

##### More Information

Bug appears on: v2.0.2
Browser: bug exists in any browser (I tested last 3 versions of `Chrome` and `Safari`)
OS: Android/IOS

**Comment by kadiryazici** [comment]
This is because of library prevents `touchstart` on swipe start, to do that I should prevent `touchmove` instead of `touchstart` I guess.

I will take a look after work.

**Comment by kadiryazici** [comment]
Currently you can use `onlyHeaderSwipe: true`, this won't prevent event on body cilck.

**Comment by hasanparasteh** [comment]
It fixed the bug.. but `bottom-sheet` has a lot of compatibility issues with touch devices..
for example click-outside won't work on mobile devices properly

**Comment by kadiryazici** [comment]
Yes it is because of preventint touch start. I will make touchmove non passive listener and prevent it instead :)

**Comment by kadiryazici** [comment]
@hasanparasteh https://github.com/kadiryazici/bottom-sheet-vue3/pull/11 I hope this fixed it
