### ISSUE TITLE
Bottom Sheet opens at wrong location

### ISSUE THREAD

**Issue by danielklein-arch** [kadiryazici/bottom-sheet-vue3#18]
-  v2.0.4

  - Brave 
  - Linux Manjaro 

 - When scrolled Bottom Sheet opens at the top instead of current scrolled location where is trigger located.

![image](https://user-images.githubusercontent.com/82767072/233603782-5bb9885b-2124-4ad3-98ef-9468de7ec159.png)

**Comment by kadiryazici** [comment]
Can you share a video?

**Comment by danielklein-arch** [comment]
![sheet](https://user-images.githubusercontent.com/82767072/233639042-f9995caf-5816-4ed6-88fe-940bb1951ee2.gif)

**Comment by danielklein-arch** [comment]
![sheet](https://user-images.githubusercontent.com/82767072/233639268-ee506779-7836-484f-86e6-5495de4dc36d.gif)

**Comment by danielklein-arch** [comment]
https://user-images.githubusercontent.com/82767072/233640081-85da7620-dcc7-4390-bf53-e69f1d282656.mp4

**Comment by kadiryazici** [comment]
I guess I forgot to make it fixed :D Fixing it.

**Comment by danielklein-arch** [comment]
Thanks a lot 😄
