### ISSUE TITLE
Vuetify integration

### ISSUE THREAD

**Issue by OmerNavon** [kadiryazici/bottom-sheet-vue3#22]
Version:
  -  v2.0.5

Environment:
chrome, 
os: 
windows 11

Issue explanation:
Module doesn't work with Vuetify 3.
its just not showing at all.
i wonder if its a local issue or a global one.

thank you
![צילום מסך 2023-06-27 110642](https://github.com/kadiryazici/bottom-sheet-vue3/assets/103376192/2bf6b9f6-125b-4a9f-af1d-0251579e1ce3)

**Comment by kadiryazici** [comment]
This package has no interaction with vuetify, can you share a reproduction?

**Comment by OmerNavon** [comment]
ok sorry, found the problem. had to change router-view z-index for some reason.
