### ISSUE TITLE
Scrollable content and fullscreen step

### ISSUE THREAD

**Issue by RoyvanEmpel** [kadiryazici/bottom-sheet-vue3#24]
**`Version (Required):`**
  - Current demo https://kadiryazici.github.io/bottom-sheet-vue3/

**`Environment (Required):`**
  - **`Browser:`** Safari, chrome, brave, firefox.
  - **`OS:`** IOS 17.4.1

**`Issue explanation (Required):`**
Would it be possible to create a sort of step/spots system like mentioned in this comment: https://github.com/kadiryazici/bottom-sheet-vue3/issues/2#issuecomment-1336612065

It would be nice to have a spot thats for example 40 dvh and then one thats 100 dvh for a fullscreen mode. The animations and swiping (inside and outside the sheet) works amazing currently.

We are having difficulties with scrollable / longer content. Atm it simply just graps the sheet and you can temporarily make it bigger / smaller.

**Comment by kadiryazici** [comment]
I got it, you want a base height and then if user starts to scroll sheet will be bigger, when the sheet becomes full screen it will let the inner content to scroll.

**Comment by kadiryazici** [comment]
Oh gosh, I now want to rewrite the library again :D 2 year old me wasn't close to current one.

**Comment by RoyvanEmpel** [comment]
> I got it, you want a base height and then if user starts to scroll sheet will be bigger, when the sheet becomes full screen it will let the inner content to scroll.

Yes thats exactly what I meant. Do you think it's possible for something like this to be added to the current version?

**Comment by kadiryazici** [comment]
I think so but curently I am busy

**Comment by kadiryazici** [comment]
@RoyvanEmpel and btw if I rewrite the library nothing will change, props and behavior will be the saem

**Comment by RoyvanEmpel** [comment]
Oh okay, so no inner scroll / steps? Or do you mean that you wil keep backwards compatibility for projects with the current version?

**Comment by kadiryazici** [comment]
I will try to implement steps but my first target will be prevent scroll until hit top of the page. Yea it will be a path or minor update not a major one
